version: '3.7'
networks:
  persist:
    name: public-net

services:
  elasticsearch:
    image: elasticsearch:7.16.3
    container_name: elasticsearch
    environment:
      TZ: Asia/Shanghai
      ES_JAVA_OPTS: -Xms248m -Xmx512m
    volumes:
      - /Users/cody/Developer/docker/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - /Users/cody/Developer/docker/elasticsearch/data:/usr/share/elasticsearch/data
      - /Users/cody/Developer/docker/elasticsearch/logs:/usr/share/elasticsearch/logs
      - /Users/cody/Developer/docker/elasticsearch/plugins:/usr/share/elasticsearch/plugins
    ports:
      - 9200:9200
    healthcheck:
      test: [ "CMD-SHELL", "curl --silent --fail localhost:9200/_cluster/health || exit 1" ]
      interval: 3s
      timeout: 1s
      retries: 5
      start_period: 10s
    networks:
      persist:
        ipv4_address: 172.20.1.3
  kibana:
    image: kibana:7.16.3
    container_name: kibana
    environment:
      TZ: Asia/Shanghai
    volumes:
      - /Users/cody/Developer/docker/kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - 5601:5601
    links:
      - elasticsearch
    depends_on:
      elasticsearch:
        condition: service_healthy
    networks:
      persist:
        ipv4_address: 172.20.1.4