version: '3.7'
networks:
  persist:
    name: public-net


services:
  mysql:
    image: mysql:8.0.29
    container_name: mysql
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: root@1234
    volumes:
      - /Users/cody/Developer/docker/mysql/data:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      persist:
        ipv4_address: 172.20.1.11