version: '3.7'
networks:
  persist:
    name: public-net


services:
  redis:
    image: redis:latest
    container_name: redis
    environment:
      TZ: Asia/Shanghai
    volumes:
      - /Users/cody/Developer/docker/redis/data:/data
      - /Users/cody/Developer/docker/redis/redis.conf:/etc/redis/redis.conf
    ports:
      - 6379:6379
    networks:
      persist:
        ipv4_address: 172.20.1.12