version: '3.7'
networks:
  persist:
    name: public-net

services:
  oap-server:
    image: apache/skywalking-oap-server:9.1.0
    container_name: oap-server
    environment:
      TZ: Asia/Shanghai
      #SW_STORAGE: elasticsearch
      #SW_STORAGE_ES_CLUSTER_NODES: 172.20.1.3:9200
      SW_STORAGE: mysql
      SW_JDBC_URL: jdbc:mysql://172.20.1.11:3306/swtest?rewriteBatchedStatements=true
      SW_HEALTH_CHECKER: default
      SW_TELEMETRY: prometheus
      SW_PROMETHEUS_FETCHER: default
      JAVA_OPTS: "-Xms248m -Xmx512m"
    volumes:
      - /Users/cody/Developer/docker/skywalking/ext-config:/skywalking/ext-config
      - /Users/cody/Developer/docker/skywalking/ext-libs:/skywalking/ext-libs
    ports:
      - 12800:12800
      - 11800:11800
    healthcheck:
      test: [ "CMD-SHELL", "/skywalking/bin/swctl ch" ]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 5s
    networks:
      persist:
        ipv4_address: 172.20.1.6

  oap-ui:
    image: apache/skywalking-ui:9.1.0
    container_name: oap-ui
    environment:
      TZ: Asia/Shanghai
      SW_OAP_ADDRESS: http://oap-server:12800
      JAVA_OPTS: "-Xms124m -Xmx248m"
    ports:
      - 18080:8080
    links:
      - oap-server
    depends_on: 
      oap-server:
        condition: service_healthy
    networks:
      persist:
        ipv4_address: 172.20.1.7
